# Generated by Django 5.1 on 2024-08-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_password_person_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='country',
            new_name='address',
        ),
    ]
