# Generated by Django 5.1 on 2024-08-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_country_person_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='speciality',
            field=models.CharField(blank=True, choices=[('1', 'العيادات الطبية لدى الشركات'), ('2', 'مرافقة الأطفال وكبار السن'), ('3', 'الأشعة المنزلية'), ('4', 'العلاج الطبيعي المنزلي'), ('5', 'زيارة طبيب في المنزل'), ('6', 'خدمات التمريض المنزلية'), ('7', 'جلسة غسيل الكلى المنزلي'), ('8', 'التحاليل الطبية المنزلية')], max_length=1, null=True),
        ),
    ]
